version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "This buildspec is based on image - aws/codebuild/standard:2.0"
      - echo "OS Environment Setup"
      - apt-get update -y
      - apt-get install awscli -y
      - pip install boto3
  pre_build:
    commands:
      - env
      - ls
      - aws s3 cp s3://myvenkat-bucket/build.py build.py --quiet
      - aws s3 cp bankTest s3://myvenkat-bucket/$CODEBUILD_START_TIME --recursive --acl bucket-owner-full-control --quiet
  build:
    commands:
      - python build.py
  post_build:
    commands:
      - ls
